name: Build on PR

on:
  workflow_dispatch:

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install Dependencies
        run: npm install
      - name: Generate child example file
        run: npm run generate
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: downloads/
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact1 # Specify the name of the artifact
          path: ./example1.txt # Specify the path to your generated file
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact1 # Specify the name of the artifact
          path: ./downloads # Specify the path to your generated file
