name: Deploy Express Server 1

on:
  workflow_dispatch:

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        id: checkout
        continue-on-error: true
        if: ${{ always() }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install Dependencies
        id: install
        run: npm install && npm dasds
        continue-on-error: true
        if: ${{ always() }}

      - name: Generate child example file
        id: generate
        run: npm run generate && npm dasds
        continue-on-error: true
        if: ${{ always() }}

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: downloads/
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact1 # Specify the name of the artifact
          path: ./example1.txt # Specify the path to your generated file

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact1 # Specify the name of the artifact
          path: ./downloads # Specify the path to your generated file
      - name: Set failed step name
        id: set_failed_step_name
        run: |
          if [ -n "${{ job.steps.checkout.outcome }}" ]; then
            echo "::set-output name=failed_step::Checkout code"
          elif [ -n "${{ job.steps.install.outcome }}" ]; then
            echo "::set-output name=failed_step::Install dependencies"
          elif [ -n "${{ job.steps.generate.outcome }}" ]; then
            echo "::set-output name=failed_step::Generate child example file"
          else
            echo "::set-output name=failed_step::Unknown step"
          fi
        if: ${{ failure() }}

      - name: Notify Notification On Faliure
        uses: ravsamhq/notify-slack-action@2.3.0
        if: always()
        with:
          status: ${{ job.status }}
          token: ${{ secrets.GITHUB_TOKEN }}
          notify_when: "failure"
          notification_title: "[Dev] ✘ Workflow *{workflow}* Faliure. Additional details: Test failed - *${{ steps.set_failed_step_name.outputs.failed_step }}*"
          message_format: null
          footer: null
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
